INSERT INTO `AfroSympla_menu_translation` (`translatable_id`, `name`, `header`, `slug`, `locale`) VALUES
(2, 'Menü im ersten Fußzeilenbereich', 'Nützliche Links', 'menu-im-ersten-fusszeilenbereich', 'de'),
(1, 'Kopfzeilenmenü', NULL, 'kopfzeilenmenu', 'de'),
(3, 'Menü für den zweiten Fußzeilenbereich', 'Mein Konto', 'menu-fur-den-zweiten-fusszeilenbereich', 'de'),
(4, 'Menü des dritten Fußzeilenabschnitts', 'Veranstaltungskategorien', 'menu-des-dritten-fusszeilenabschnitts', 'de'),
(1, 'Menu de cabeçalho', NULL, 'menu-de-cabecalho', 'pt'),
(2, 'Menu da seção do primeiro rodapé', 'Links Úteis', 'menu-da-secao-do-primeiro-rodape', 'pt'),
(3, 'Menu da seção do segundo rodapé', 'Minha conta', 'menu-da-secao-do-segundo-rodape', 'pt'),
(4, 'Menu da seção do terceiro rodapé', 'Categorias de Eventos', 'menu-da-secao-do-terceiro-rodape', 'pt');

INSERT INTO `AfroSympla_amenity_translation` (`translatable_id`, `name`, `slug`, `locale`) VALUES
(5, 'Spa', 'spa-3\r\n', 'de'),
(6, 'Direkt am Strand', 'direkt-am-strand', 'de'),
(7, 'Geschäftszentrum', 'geschaeftszentrum', 'de'),
(8, 'Barrierefrei', 'barrierefrei', 'de'),
(9, 'Außenraum', 'aussenraum', 'de'),
(17, 'Theaterraum', 'theaterraum', 'de'),
(16, 'Dachterasse', 'dachterasse', 'de'),
(15, 'Medienraum', 'medienraum', 'de'),
(14, 'Parken', 'parken', 'de'),
(13, 'Breakout-Räume', 'breakout-raeume', 'de'),
(12, 'A/V-Ausrüstung', 'av-ausruestung', 'de'),
(11, 'Wifi', 'wifi-3', 'de'),
(10, 'Haustierfreundlich', 'haustierfreundlich', 'de'),
(17, 'Espaço de teatro', 'espaco-de-teatro', 'pt'),
(16, 'Telhado', 'telhado', 'pt'),
(15, 'Sala de mídia', 'sala-de-midia', 'pt'),
(14, 'Estacionamento', 'estacionamento', 'pt'),
(13, 'Salas de descanso', 'salas-de-descanso-1', 'pt'),
(12, 'Equipamento A / V', 'equipamento-a-v', 'pt'),
(11, 'Wi-fi', 'wi-fi', 'pt'),
(10, 'Animais de estimação', 'animais-de-estimacao', 'pt'),
(9, 'Espaço ao Ar Livre', 'espaco-ao-ar-livre', 'pt'),
(8, 'Acessível para deficientes', 'acessivel-para-deficientes', 'pt'),
(7, 'Centro de negócios', 'centro-de-negocios-1', 'pt'),
(6, 'À beira-mar', 'a-beira-mar', 'pt'),
(5, 'Spa', 'spa-3', 'pt');

INSERT INTO `AfroSympla_menu_element_translation` (`translatable_id`, `label`, `slug`, `locale`) VALUES
(1, 'Casa', 'casa', 'pt'),
(1, 'Heim', 'heim', 'de'),
(2, 'Eventos', 'eventos', 'pt'),
(2, 'Veranstaltungen', 'veranstaltungen', 'de'),
(3, 'Explorar', 'explorar-1', 'pt'),
(3, 'Entdecken', 'entdecken', 'de'),
(4, 'Locais', 'locais', 'pt'),
(4, 'Veranstaltungsorte', 'veranstaltungsorte', 'de'),
(5, 'Como funciona?', 'como-funciona-1', 'pt'),
(5, 'Wie es funktioniert?', 'wie-es-funktioniert', 'de'),
(6, 'Blog', 'blog-6', 'pt'),
(6, 'Blog', 'blog-7', 'de'),
(7, 'Meus ingressos', 'meus-ingressos', 'pt'),
(7, 'Meine Tickets', 'meine-tickets', 'de'),
(8, 'Adicionar meu evento', 'adicionar-meu-evento', 'pt'),
(8, 'Veranstaltung hinzufügen', 'veranstaltung-hinzufuegen', 'de'),
(9, 'Sobre nós', 'sobre-nos', 'pt'),
(9, 'Über uns', 'ueber-uns', 'de'),
(10, 'Centro de ajuda', 'centro-de-ajuda', 'pt'),
(10, 'Hilfezentrum', 'hilfezentrum', 'de'),
(11, 'Blog', 'blog-8', 'pt'),
(11, 'Blog', 'blog-9', 'de'),
(12, 'Locais', 'locais-1', 'pt'),
(12, 'Veranstaltungsorte', 'veranstaltungsorte-1', 'de'),
(13, 'Envie-nos um e-mail', 'envie-nos-um-e-mail', 'pt'),
(13, 'senden Sie uns eine Email', 'senden-sie-uns-eine-email', 'de'),
(14, 'Crie a sua conta aqui', 'crie-a-sua-conta-aqui', 'pt'),
(14, 'Ein Konto erstellen', 'ein-konto-erstellen', 'de'),
(15, 'Venda ingressos online', 'venda-ingressos-online', 'pt'),
(15, 'Tickets online verkaufen', 'tickets-online-verkaufen', 'de'),
(16, 'Meus ingressos', 'meus-ingressos-1', 'pt'),
(16, 'Meine Tickets', 'meine-tickets-1', 'de'),
(17, 'Esqueceu sua senha ?', 'esqueceu-sua-senha', 'pt'),
(17, 'Passwort vergessen ?', 'passwort-vergessen', 'de'),
(18, 'Preços e taxas', 'precos-e-taxas', 'pt'),
(18, 'Preise und Gebühren', 'preise-und-gebuehren', 'de');

INSERT INTO `AfroSympla_blog_post_category_translation` (`translatable_id`, `name`, `slug`, `locale`) VALUES
(17, 'Planejamento', 'planejamento', 'pt'),
(17, 'Planung', 'planung', 'de'),
(16, 'Pontas', 'pontas', 'pt'),
(16, 'Tipps', 'tipps', 'de'),
(15, 'De outros', 'de-outros', 'pt'),
(15, 'Sonstiges', 'sonstiges', 'de'),
(14, 'Patrocinando', 'patrocinando', 'pt'),
(14, 'Sponsoring', 'sponsoring-1', 'de'),
(13, 'Mídia social', 'midia-social', 'pt'),
(13, 'Sozialen Medien', 'sozialen-medien', 'de'),
(12, 'Marketing', 'marketing-2', 'pt'),
(12, 'Marketing', 'marketing-3', 'de'),
(11, 'Preços', 'precos', 'pt'),
(11, 'Preisgestaltung', 'preisgestaltung', 'de'),
(10, 'Notícia', 'noticia', 'pt'),
(10, 'Nachrichten', 'nachrichten', 'de'),
(9, 'Recurso', 'recurso', 'pt'),
(9, 'Besonderheit', 'besonderheit', 'de'),
(8, 'Conteúdo', 'conteudo', 'pt'),
(8, 'Inhalt', 'inhalt', 'de'),
(7, 'Comunidade', 'comunidade', 'pt'),
(7, 'Gemeinschaft', 'gemeinschaft', 'de'),
(6, 'Colaboração', 'colaboracao', 'pt'),
(6, 'Zusammenarbeit', 'zusammenarbeit', 'de'),
(5, 'Refeições', 'refeicoes', 'pt'),
(5, 'Gastronomie', 'gastronomie', 'de'),
(4, 'Orçamentação', 'orcamentacao', 'pt'),
(4, 'Budgetierung', 'budgetierung', 'de'),
(3, 'Branding', 'branding-1', 'pt'),
(3, 'Markenzeichen', 'markenzeichen', 'de'),
(2, 'Participantes', 'participantes', 'pt'),
(2, 'Teilnehmerinnen', 'teilnehmerinnen', 'de');

INSERT INTO `AfroSympla_audience_translation` (`translatable_id`, `name`, `slug`, `locale`) VALUES
(2, 'Crianças', 'criancas', 'pt'),
(2, 'Kinder', 'kinder', 'de'),
(1, 'Adultos', 'adultos-1', 'pt'),
(1, 'Erwachsene', 'erwachsene', 'de'),
(5, 'Juventude', 'juventude', 'pt'),
(5, 'Jugend', 'jugend', 'de'),
(4, 'Grupo', 'grupo-1', 'pt'),
(4, 'Gruppe', 'gruppe', 'de'),
(3, 'Família', 'familia-1', 'pt'),
(3, 'Familie', 'familie', 'de');

INSERT INTO `AfroSympla_category_translation` (`translatable_id`, `name`, `slug`, `locale`) VALUES
(15, 'De outros', 'de-outros', 'pt'),
(15, 'Andere', 'andere', 'de'),
(14, 'Estacionamento / Serviços', 'estacionamento-servicos', 'pt'),
(14, 'Parking / Services', 'parking-services-2', 'de'),
(13, 'Parque de recreação / atração', 'parque-de-recreacao-atracao', 'pt'),
(13, 'Erholungspark / Sehenswürdigkeit', 'erholungspark-sehenswuerdigkeit', 'de'),
(12, 'Restaurante / Gastronomia', 'restaurante-gastronomia-1', 'pt'),
(12, 'Restaurant / Gastronomie', 'restaurant-gastronomie-1', 'de'),
(11, 'Museu / Monumento', 'museu-monumento', 'pt'),
(11, 'Museum / Denkmal', 'museum-denkmal', 'de'),
(10, 'Esporte / Fitness', 'esporte-fitness', 'pt'),
(10, 'Sport / Fitness', 'sport-fitness-2', 'de'),
(9, 'Exposição', 'exposicao', 'pt'),
(9, 'Exposition', 'exposition-2', 'de'),
(8, 'Jogo / Competição', 'jogo-competicao', 'pt'),
(8, 'Spiel / Wettbewerb', 'spiel-wettbewerb', 'de'),
(7, 'Festival / Espetáculo', 'festival-espetaculo', 'pt'),
(7, 'Festival / Spektakel', 'festival-spektakel', 'de'),
(6, 'Conferência', 'conferencia-1', 'pt'),
(6, 'Konferenz', 'konferenz', 'de'),
(5, 'Oficina / Treinamento', 'oficina-treinamento', 'pt'),
(5, 'Werkstatt / Schulung', 'werkstatt-schulung', 'de'),
(4, 'Viagem / acampamento', 'viagem-acampamento', 'pt'),
(4, 'Ausflug / Lager', 'ausflug-lager', 'de'),
(3, 'Concerto / Música', 'concerto-musica', 'pt'),
(3, 'Konzert / Musik', 'konzert-musik', 'de'),
(2, 'Teatro', 'teatro-1', 'pt'),
(2, 'Theater', 'theater-1', 'de'),
(1, 'Cinema', 'cinema-2', 'pt'),
(1, 'Kino', 'kino', 'de');

INSERT INTO `AfroSympla_language_translation` (`translatable_id`, `name`, `slug`, `locale`) VALUES
(1, 'Inglês', 'english-pt', 'pt'),
(1, 'Englisch', 'english-de', 'de'),
(2, 'Longe', 'afar-pt', 'pt'),
(2, 'Fern', 'afar-de', 'de'),
(3, 'Abecásio', 'abkhazian-pt', 'pt'),
(3, 'Abchasisch', 'abkhazian-de', 'de'),
(4, 'Afrikaans', 'afrikaans-pt', 'pt'),
(4, 'Afrikaans', 'afrikaans-de', 'de'),
(5, 'Amárico', 'amharic-pt', 'pt'),
(5, 'Amharisch', 'amharic-de', 'de'),
(6, 'árabe', 'arabic-pt', 'pt'),
(6, 'Arabisch', 'arabic-de', 'de'),
(7, 'Assamês', 'assamese-pt', 'pt'),
(7, 'Assamesisch', 'assamese-de', 'de'),
(8, 'Aimará', 'aymara-pt', 'pt'),
(8, 'Aymara', 'aymara-de', 'de'),
(9, 'Azerbaijani', 'azerbaijani-pt', 'pt'),
(9, 'Aserbaidschanisch', 'azerbaijani-de', 'de'),
(10, 'Bashkir', 'bashkir-pt', 'pt'),
(10, 'Baschkirisch', 'bashkir-de', 'de'),
(11, 'Bielo-russo', 'byelorussian-pt', 'pt'),
(11, 'Weißrussisch', 'byelorussian-de', 'de'),
(12, 'Búlgaro', 'bulgarian-pt', 'pt'),
(12, 'Bulgarisch', 'bulgarian-de', 'de'),
(13, 'Bihari', 'bihari-pt', 'pt'),
(13, 'Bihari', 'bihari-de', 'de'),
(14, 'Bislama', 'bislama-pt', 'pt'),
(14, 'Bislama', 'bislama-de', 'de'),
(15, 'Bengali / Bangla', 'bengalibangla-pt', 'pt'),
(15, 'Bengalisch/Bangla', 'bengalibangla-de', 'de'),
(16, 'Tibetano', 'tibetan-pt', 'pt'),
(16, 'Tibetisch', 'tibetan-de', 'de'),
(17, 'Bretão', 'breton-pt', 'pt'),
(17, 'Bretonisch', 'breton-de', 'de'),
(18, 'Catalão', 'catalan-pt', 'pt'),
(18, 'Katalanisch', 'catalan-de', 'de'),
(19, 'Corso', 'corsican-pt', 'pt'),
(19, 'Korsisch', 'corsican-de', 'de'),
(20, 'Tcheco', 'czech-pt', 'pt'),
(20, 'Tschechisch', 'czech-de', 'de'),
(21, 'Galês', 'welsh-pt', 'pt'),
(21, 'Walisisch', 'welsh-de', 'de'),
(22, 'Dinamarquês', 'danish-pt', 'pt'),
(22, 'Dänisch', 'danish-de', 'de'),
(23, 'Alemão', 'german-pt', 'pt'),
(23, 'Deutsch', 'german-de', 'de'),
(24, 'Butani', 'bhutani-pt', 'pt'),
(24, 'Bhutani', 'bhutani-de', 'de'),
(25, 'Grego', 'greek-pt', 'pt'),
(25, 'Griechisch', 'greek-de', 'de'),
(26, 'Esperanto', 'esperanto-pt', 'pt'),
(26, 'Esperanto', 'esperanto-de', 'de'),
(27, 'Espanhol', 'spanish-pt', 'pt'),
(27, 'Spanisch', 'spanish-de', 'de'),
(28, 'Estoniano', 'estonian-pt', 'pt'),
(28, 'Estnisch', 'estonian-de', 'de'),
(29, 'Basco', 'basque-pt', 'pt'),
(29, 'Baskisch', 'basque-de', 'de'),
(30, 'Persa', 'persian-pt', 'pt'),
(30, 'Persisch', 'persian-de', 'de'),
(31, 'Finlandês', 'finnish-pt', 'pt'),
(31, 'Finnisch', 'finnish-de', 'de'),
(32, 'Fiji', 'fiji-pt', 'pt'),
(32, 'Fidschi', 'fiji-de', 'de'),
(33, 'Feroês', 'faeroese-pt', 'pt'),
(33, 'Färöer', 'faeroese-de', 'de'),
(34, 'Francês', 'french-pt', 'pt'),
(34, 'Französisch', 'french-de', 'de'),
(35, 'Frísio', 'frisian-pt', 'pt'),
(35, 'Friesisch', 'frisian-de', 'de'),
(36, 'Irlandês', 'irish-pt', 'pt'),
(36, 'Irisch', 'irish-de', 'de'),
(37, 'Escocês / gaélico', 'scotsgaelic-pt', 'pt'),
(37, 'Schottisch/Gälisch', 'scotsgaelic-de', 'de'),
(38, 'Galego', 'galician-pt', 'pt'),
(38, 'Galizisch', 'galician-de', 'de'),
(39, 'Guarani', 'guarani-pt', 'pt'),
(39, 'Guarani', 'guarani-de', 'de'),
(40, 'Gujarati', 'gujarati-pt', 'pt'),
(40, 'Gujarati', 'gujarati-de', 'de'),
(41, 'Hausa', 'hausa-pt', 'pt'),
(41, 'Hausa', 'hausa-de', 'de'),
(42, 'Hindi', 'hindi-pt', 'pt'),
(42, 'Hindi', 'hindi-de', 'de'),
(43, 'Croata', 'croatian-pt', 'pt'),
(43, 'Kroatisch', 'croatian-de', 'de'),
(44, 'Húngaro', 'hungarian-pt', 'pt'),
(44, 'Ungarisch', 'hungarian-de', 'de'),
(45, 'Armênio', 'armenian-pt', 'pt'),
(45, 'Armenisch', 'armenian-de', 'de'),
(46, 'Interlíngua', 'interlingua-pt', 'pt'),
(46, 'Interlingua', 'interlingua-de', 'de'),
(47, 'Interlingue', 'interlingue-pt', 'pt'),
(47, 'Zwischensprache', 'interlingue-de', 'de'),
(48, 'Inupiak', 'inupiak-pt', 'pt'),
(48, 'Inupiak', 'inupiak-de', 'de'),
(49, 'Indonésio', 'indonesian-pt', 'pt'),
(49, 'Indonesisch', 'indonesian-de', 'de'),
(50, 'Islandês', 'icelandic-pt', 'pt'),
(50, 'Isländisch', 'icelandic-de', 'de'),
(51, 'Italiano', 'italian-pt', 'pt'),
(51, 'Italienisch', 'italian-de', 'de'),
(52, 'Hebraico', 'hebrew-pt', 'pt'),
(52, 'Hebräisch', 'hebrew-de', 'de'),
(53, 'Japonês', 'japanese-pt', 'pt'),
(53, 'Japanisch', 'japanese-de', 'de'),
(54, 'Iídiche', 'yiddish-pt', 'pt'),
(54, 'Jiddisch', 'yiddish-de', 'de'),
(55, 'Javanês', 'javanese-pt', 'pt'),
(55, 'Javanisch', 'javanese-de', 'de'),
(56, 'Georgiano', 'georgian-pt', 'pt'),
(56, 'Georgisch', 'georgian-de', 'de'),
(57, 'Cazaque', 'kazakh-pt', 'pt'),
(57, 'Kasachisch', 'kazakh-de', 'de'),
(58, 'Groenlandês', 'greenlandic-pt', 'pt'),
(58, 'Grönländisch', 'greenlandic-de', 'de'),
(59, 'Cambojano', 'cambodian-pt', 'pt'),
(59, 'Kambodschanisch', 'cambodian-de', 'de'),
(60, 'Canarim', 'kannada-pt', 'pt'),
(60, 'Kannada', 'kannada-de', 'de'),
(61, 'Coreano', 'korean-pt', 'pt'),
(61, 'Koreanisch', 'korean-de', 'de'),
(62, 'Caxemira', 'kashmiri-pt', 'pt'),
(62, 'Kaschmir', 'kashmiri-de', 'de'),
(63, 'Curdo', 'kurdish-pt', 'pt'),
(63, 'Kurdisch', 'kurdish-de', 'de'),
(64, 'Quirguiz', 'kirghiz-pt', 'pt'),
(64, 'Kirgisien', 'kirghiz-de', 'de'),
(65, 'Latina', 'latin-pt', 'pt'),
(65, 'Latein', 'latin-de', 'de'),
(66, 'Lingala', 'lingala-pt', 'pt'),
(66, 'Lingala', 'lingala-de', 'de'),
(67, 'Laosiano', 'laothian-pt', 'pt'),
(67, 'Laothisch', 'laothian-de', 'de'),
(68, 'Lituano', 'lithuanian-pt', 'pt'),
(68, 'Litauisch', 'lithuanian-de', 'de'),
(69, 'Letão / letão', 'latvianlettish-pt', 'pt'),
(69, 'Lettisch/Lettisch', 'latvianlettish-de', 'de'),
(70, 'Malgaxe', 'malagasy-pt', 'pt'),
(70, 'Madagassisch', 'malagasy-de', 'de'),
(71, 'Maori', 'maori-pt', 'pt'),
(71, 'Maori', 'maori-de', 'de'),
(72, 'Macedônio', 'macedonian-pt', 'pt'),
(72, 'Mazedonisch', 'macedonian-de', 'de'),
(73, 'Malaiala', 'malayalam-pt', 'pt'),
(73, 'Malayalam', 'malayalam-de', 'de'),
(74, 'Mongol', 'mongolian-pt', 'pt'),
(74, 'Mongolisch', 'mongolian-de', 'de'),
(75, 'Da Moldávia', 'moldavian-pt', 'pt'),
(75, 'Moldauisch', 'moldavian-de', 'de'),
(76, 'Marathi', 'marathi-pt', 'pt'),
(76, 'Marathi', 'marathi-de', 'de'),
(77, 'Malaio', 'malay-pt', 'pt'),
(77, 'Malaiisch', 'malay-de', 'de'),
(78, 'Maltês', 'maltese-pt', 'pt'),
(78, 'Maltesisch', 'maltese-de', 'de'),
(79, 'Birmanês', 'burmese-pt', 'pt'),
(79, 'Birmanisch', 'burmese-de', 'de'),
(80, 'Nauru', 'nauru-pt', 'pt'),
(80, 'Nauru', 'nauru-de', 'de'),
(81, 'Nepalês', 'nepali-pt', 'pt'),
(81, 'Nepali', 'nepali-de', 'de'),
(82, 'Holandês', 'dutch-pt', 'pt'),
(82, 'Niederländisch', 'dutch-de', 'de'),
(83, 'Norueguês', 'norwegian-pt', 'pt'),
(83, 'Norwegisch', 'norwegian-de', 'de'),
(84, 'Occitano', 'occitan-pt', 'pt'),
(84, 'Okzitanisch', 'occitan-de', 'de'),
(85, '(Afan)/Oromoor/Oriya', 'afanoromoororiya-pt', 'pt'),
(85, '(Afan)/Oromoor/Oriya', 'afanoromoororiya-de', 'de'),
(86, 'Punjabi', 'punjabi-pt', 'pt'),
(86, 'Punjabi', 'punjabi-de', 'de'),
(87, 'Polonês', 'polish-pt', 'pt'),
(87, 'Polieren', 'polish-de', 'de'),
(88, 'Pashto / pachto', 'pashtopushto-pt', 'pt'),
(88, 'Pashto/Pushto', 'pashtopushto-de', 'de'),
(89, 'Português', 'portuguese-pt', 'pt'),
(89, 'Portugiesisch', 'portuguese-de', 'de'),
(90, 'Quechua', 'quechua-pt', 'pt'),
(90, 'Quechua', 'quechua-de', 'de'),
(91, 'Raeto-Romance', 'rhaeto-romance-pt', 'pt'),
(91, 'Rätoromanisch', 'rhaeto-romance-de', 'de'),
(92, 'Kirundi', 'kirundi-pt', 'pt'),
(92, 'Kirundi', 'kirundi-de', 'de'),
(93, 'Romena', 'romanian-pt', 'pt'),
(93, 'Rumänisch', 'romanian-de', 'de'),
(94, 'Russo', 'russian-pt', 'pt'),
(94, 'Russisch', 'russian-de', 'de'),
(95, 'Kinyarwanda', 'kinyarwanda-pt', 'pt'),
(95, 'Kinyarwanda', 'kinyarwanda-de', 'de'),
(96, 'Sânscrito', 'sanskrit-pt', 'pt'),
(96, 'Sanskrit', 'sanskrit-de', 'de'),
(97, 'Sindi', 'sindhi-pt', 'pt'),
(97, 'Sindhi', 'sindhi-de', 'de'),
(98, 'Sangro', 'sangro-pt', 'pt'),
(98, 'Sangro', 'sangro-de', 'de'),
(99, 'Servo-croata', 'serbo-croatian-pt', 'pt'),
(99, 'Serbokroatisch', 'serbo-croatian-de', 'de'),
(100, 'Cingalês', 'singhalese-pt', 'pt'),
(100, 'Singhalesisch', 'singhalese-de', 'de'),
(101, 'Eslovaco', 'slovak-pt', 'pt'),
(101, 'Slowakisch', 'slovak-de', 'de'),
(102, 'Esloveno', 'slovenian-pt', 'pt'),
(102, 'Slowenisch', 'slovenian-de', 'de'),
(103, 'Samoano', 'samoan-pt', 'pt'),
(103, 'Samoanisch', 'samoan-de', 'de'),
(104, 'Shona', 'shona-pt', 'pt'),
(104, 'Shona', 'shona-de', 'de'),
(105, 'Somali', 'somali-pt', 'pt'),
(105, 'Somali', 'somali-de', 'de'),
(106, 'Albanês', 'albanian-pt', 'pt'),
(106, 'Albanisch', 'albanian-de', 'de'),
(107, 'Sérvio', 'serbian-pt', 'pt'),
(107, 'Serbisch', 'serbian-de', 'de'),
(108, 'Siswati', 'siswati-pt', 'pt'),
(108, 'Siswati', 'siswati-de', 'de'),
(109, 'Sesotho', 'sesotho-pt', 'pt'),
(109, 'Sesotho', 'sesotho-de', 'de'),
(110, 'Sundanês', 'sundanese-pt', 'pt'),
(110, 'Sundanesisch', 'sundanese-de', 'de'),
(111, 'Sueco', 'swedish-pt', 'pt'),
(111, 'Schwedisch', 'swedish-de', 'de'),
(112, 'Suaíli', 'swahili-pt', 'pt'),
(112, 'Swahili', 'swahili-de', 'de'),
(113, 'Tâmil', 'tamil-pt', 'pt'),
(113, 'Tamil', 'tamil-de', 'de'),
(114, 'Telugu', 'tegulu-pt', 'pt'),
(114, 'Telugu', 'tegulu-de', 'de'),
(115, 'Tadjique', 'tajik-pt', 'pt'),
(115, 'Tadschikisch', 'tajik-de', 'de'),
(116, 'Tailandês', 'thai-pt', 'pt'),
(116, 'Thai', 'thai-de', 'de'),
(117, 'Tigrinya', 'tigrinya-pt', 'pt'),
(117, 'Tigrinya', 'tigrinya-de', 'de'),
(118, 'Turcomano', 'turkmen-pt', 'pt'),
(118, 'Turkmenen', 'turkmen-de', 'de'),
(119, 'Tagalo', 'tagalog-pt', 'pt'),
(119, 'Tagalog', 'tagalog-de', 'de'),
(120, 'Setswana', 'setswana-pt', 'pt'),
(120, 'Setswana', 'setswana-de', 'de'),
(121, 'Tonga', 'tonga-pt', 'pt'),
(121, 'Tonga', 'tonga-de', 'de'),
(122, 'Turco', 'turkish-pt', 'pt'),
(122, 'Türkisch', 'turkish-de', 'de'),
(123, 'Tsonga', 'tsonga-pt', 'pt'),
(123, 'Tsonga', 'tsonga-de', 'de'),
(124, 'Tártaro', 'tatar-pt', 'pt'),
(124, 'Tatar', 'tatar-de', 'de'),
(125, 'Twi', 'twi-pt', 'pt'),
(125, 'Zwei', 'twi-de', 'de'),
(126, 'Ucraniano', 'ukrainian-pt', 'pt'),
(126, 'Ukrainisch', 'ukrainian-de', 'de'),
(127, 'Urdu', 'urdu-pt', 'pt'),
(127, 'Urdu', 'urdu-de', 'de'),
(128, 'Usbeque', 'uzbek-pt', 'pt'),
(128, 'Usbekisch', 'uzbek-de', 'de'),
(129, 'Vietnamita', 'vietnamese-pt', 'pt'),
(129, 'Vietnamesisch', 'vietnamese-de', 'de'),
(130, 'Volapuk', 'volapuk-pt', 'pt'),
(130, 'Volapuk', 'volapuk-de', 'de'),
(131, 'Wolof', 'wolof-pt', 'pt'),
(131, 'Wolof', 'wolof-de', 'de'),
(132, 'Xhosa', 'xhosa-pt', 'pt'),
(132, 'Xhosa', 'xhosa-de', 'de'),
(133, 'Ioruba', 'yoruba-pt', 'pt'),
(133, 'Yoruba', 'yoruba-de', 'de'),
(134, 'Chinês', 'chinese-pt', 'pt'),
(134, 'Chinesisch', 'chinese-de', 'de'),
(135, 'Zulu', 'zulu-pt', 'pt'),
(135, 'Zulu-', 'zulu-de', 'de');

INSERT INTO `AfroSympla_country_translation` (`translatable_id`, `name`, `slug`, `locale`) VALUES
(162, 'Cabo Verde', 'cabo-verde-1', 'pt'),
(162, 'Kap Verde', 'kap-verde', 'de'),
(163, 'Cuba', 'cuba-3', 'pt'),
(163, 'Kuba', 'kuba', 'de'),
(178, 'Eslovênia', 'eslovenia-1', 'pt'),
(178, 'Slowenien', 'slowenien', 'de'),
(179, 'Coréia do Norte', 'coreia-do-norte', 'pt'),
(179, 'Nord Korea', 'nord-korea', 'de'),
(194, 'Ilhas Virgens Britânicas', 'ilhas-virgens-britanicas', 'pt'),
(194, 'Britische Jungferninseln', 'britische-jungferninseln', 'de'),
(195, 'Alemanha', 'alemanha', 'pt'),
(195, 'Deutschland', 'deutschland', 'de'),
(210, 'Liechtenstein', 'liechtenstein-2', 'pt'),
(210, 'Liechtenstein', 'liechtenstein-3', 'de'),
(211, 'Letônia', 'letonia-1', 'pt'),
(211, 'Lettland', 'lettland', 'de'),
(226, 'Andorra', 'andorra-2', 'pt'),
(226, 'Andorra', 'andorra-3', 'de'),
(242, 'Índia', 'india-2', 'pt'),
(242, 'Indien', 'indien', 'de'),
(156, 'República Democrática do Congo', 'republica-democratica-do-congo', 'pt'),
(156, 'Demokratische Republik Kongo', 'demokratische-republik-kongo', 'de'),
(157, 'República Checa', 'republica-checa-1', 'pt'),
(157, 'Tschechien', 'tschechien', 'de'),
(172, 'Camboja', 'camboja', 'pt'),
(172, 'Kambodscha', 'kambodscha', 'de'),
(173, 'São Cristóvão e Neves', 'sao-cristovao-e-neves', 'pt'),
(173, 'St. Kitts und Nevis', 'st-kitts-und-nevis', 'de'),
(188, 'Suécia', 'suecia-1', 'pt'),
(188, 'Schweden', 'schweden', 'de'),
(204, 'Laos', 'laos-3', 'pt'),
(204, 'Laos', 'laos-4', 'de'),
(219, 'Togo', 'togo-3', 'pt'),
(219, 'Togo', 'togo-4', 'de'),
(220, 'Chade', 'chade', 'pt'),
(220, 'Tschad', 'tschad', 'de'),
(235, 'Angola', 'angola-3', 'pt'),
(235, 'Angola', 'angola-4', 'de'),
(236, 'Antártica', 'antartica', 'pt'),
(236, 'Antarktis', 'antarktis', 'de'),
(158, 'Chipre', 'chipre-1', 'pt'),
(158, 'Zypern', 'zypern', 'de'),
(174, 'Comores', 'comores-1', 'pt'),
(174, 'Komoren', 'komoren', 'de'),
(189, 'Sudan', 'sudan-2', 'pt'),
(189, 'Sudan', 'sudan-3', 'de'),
(190, 'República Dominicana', 'republica-dominicana-1', 'pt'),
(190, 'Dominikanische Republik', 'dominikanische-republik', 'de'),
(205, 'Tuvalu', 'tuvalu-3', 'pt'),
(205, 'Tuvalu', 'tuvalu-4', 'de'),
(206, 'Taiwan', 'taiwan-3', 'pt'),
(206, 'Taiwan', 'taiwan-4', 'de'),
(221, 'Ilhas Turcas e Caicos', 'ilhas-turcas-e-caicos', 'pt'),
(221, 'Turks- und Caicosinseln', 'turks-und-caicosinseln', 'de'),
(222, 'Líbia', 'libia-1', 'pt'),
(222, 'Libyen', 'libyen', 'de'),
(237, 'Samoa Americana', 'samoa-americana-1', 'pt'),
(237, 'Amerikanischen Samoa-Inseln', 'amerikanischen-samoa-inseln', 'de'),
(238, 'Argentina', 'argentina-2', 'pt'),
(238, 'Argentinien', 'argentinien', 'de'),
(13, 'Burundi', 'burundi-3', 'pt'),
(13, 'Burundi', 'burundi-4', 'de'),
(14, 'Benin', 'benin-3', 'pt'),
(14, 'Benin', 'benin-4', 'de'),
(29, 'Timor Leste', 'timor-leste', 'pt'),
(29, 'Osttimor', 'osttimor', 'de'),
(45, 'Guiana Francesa', 'guiana-francesa', 'pt'),
(45, 'Französisch-Guayana', 'franzoesisch-guayana', 'de'),
(61, 'Hungria', 'hungria-1', 'pt'),
(61, 'Ungarn', 'ungarn', 'de'),
(77, 'Paquistão', 'paquistao', 'pt'),
(77, 'Pakistan', 'pakistan-3', 'de'),
(93, 'Zimbábue', 'zimbabue-1', 'pt'),
(93, 'Zimbabwe', 'zimbabwe-2', 'de'),
(109, 'Macedonia', 'macedonia-3', 'pt'),
(109, 'Mazedonien', 'mazedonien', 'de'),
(125, 'Santa Helena', 'santa-helena-1', 'pt'),
(125, 'Heilige Helena', 'heilige-helena', 'de'),
(141, 'Nepal', 'nepal-3', 'pt'),
(141, 'Nepal', 'nepal-4', 'de'),
(15, 'Butão', 'butao', 'pt'),
(15, 'Bhutan', 'bhutan-1', 'de'),
(31, 'Turcomenistão', 'turcomenistao', 'pt'),
(31, 'Turkmenistan', 'turkmenistan-3', 'de'),
(46, 'Geórgia', 'georgia-2', 'pt'),
(46, 'Georgia', 'georgia-3', 'de'),
(62, 'Hong Kong', 'hong-kong-3', 'pt'),
(62, 'Hong Kong', 'hong-kong-4', 'de'),
(78, 'Filipinas', 'filipinas', 'pt'),
(78, 'Philippinen', 'philippinen', 'de'),
(94, 'Arábia Saudita', 'arabia-saudita-1', 'pt'),
(94, 'Saudi-Arabien', 'saudi-arabien', 'de'),
(110, 'Maurício', 'mauricio-1', 'pt'),
(110, 'Mauritius', 'mauritius-1', 'de'),
(126, 'Finland', 'finland-1', 'pt'),
(126, 'Finnland', 'finnland', 'de'),
(142, 'Nauru', 'nauru-3', 'pt'),
(142, 'Nauru', 'nauru-4', 'de'),
(16, 'Jamaica', 'jamaica-2', 'pt'),
(16, 'Jamaika', 'jamaika', 'de'),
(32, 'Tajiquistão', 'tajiquistao', 'pt'),
(32, 'Tadschikistan', 'tadschikistan', 'de'),
(47, 'Grenada', 'grenada-1', 'pt'),
(47, 'Grenada', 'grenada-2', 'de'),
(48, 'Reino Unido', 'reino-unido-1', 'pt'),
(48, 'Vereinigtes Königreich', 'vereinigtes-koenigreich', 'de'),
(63, 'Honduras', 'honduras-3', 'pt'),
(63, 'Honduras', 'honduras-4', 'de'),
(79, 'Pitcairn', 'pitcairn-3', 'pt'),
(79, 'Pitcairn', 'pitcairn-4', 'de'),
(95, 'Espanha', 'espanha', 'pt'),
(95, 'Spanien', 'spanien', 'de'),
(111, 'Malta', 'malta-2', 'pt'),
(111, 'Malta', 'malta-3', 'de'),
(127, 'Fiji', 'fiji-1', 'pt'),
(127, 'Fidschi', 'fidschi', 'de'),
(143, 'Niue', 'niue-3', 'pt'),
(143, 'Niue', 'niue-4', 'de'),
(1, 'Bangladesh', 'bangladesh-3', 'pt'),
(1, 'Bangladesch', 'bangladesch', 'de'),
(17, 'Ilha Bouvet', 'ilha-bouvet', 'pt'),
(17, 'Bouvet-Insel', 'bouvet-insel', 'de'),
(33, 'Romênia', 'romenia', 'pt'),
(33, 'Rumänien', 'rumaenien', 'de'),
(49, 'Gabão', 'gabao', 'pt'),
(49, 'Gabun', 'gabun', 'de'),
(64, 'Ilha Heard e Ilhas McDonald', 'ilha-heard-e-ilhas-mcdonald', 'pt'),
(64, 'Heard-Insel und McDonald-Inseln', 'heard-insel-und-mcdonald-inseln', 'de'),
(80, 'Polônia', 'polonia-1', 'pt'),
(80, 'Polen', 'polen', 'de'),
(96, 'Eritreia', 'eritreia', 'pt'),
(96, 'Eritrea', 'eritrea-2', 'de'),
(112, 'Malawi', 'malawi-3', 'pt'),
(112, 'Malawi', 'malawi-4', 'de'),
(128, 'Ilhas Malvinas', 'ilhas-malvinas', 'pt'),
(128, 'Falkland Inseln', 'falkland-inseln', 'de'),
(144, 'Ilhas Cook', 'ilhas-cook', 'pt'),
(144, 'Cookinseln', 'cookinseln', 'de'),
(2, 'Bélgica', 'belgica-1', 'pt'),
(2, 'Belgien', 'belgien', 'de'),
(18, 'Botswana', 'botswana-2', 'pt'),
(18, 'Botswana', 'botswana-3', 'de'),
(34, 'Tokelau', 'tokelau-3', 'pt'),
(34, 'Tokelau', 'tokelau-4', 'de'),
(50, 'El Salvador', 'el-salvador-2', 'pt'),
(50, 'El Salvador', 'el-salvador-3', 'de'),
(65, 'Venezuela', 'venezuela-3', 'pt'),
(65, 'Venezuela', 'venezuela-4', 'de'),
(81, 'São Pedro e Miquelão', 'sao-pedro-e-miquelao', 'pt'),
(81, 'Saint Pierre und Miquelon', 'saint-pierre-und-miquelon', 'de'),
(97, 'Montenegro', 'montenegro-3', 'pt'),
(97, 'Montenegro', 'montenegro-4', 'de'),
(113, 'Maldivas', 'maldivas', 'pt'),
(113, 'Malediven', 'malediven', 'de'),
(129, 'Micronésia', 'micronesia-2', 'pt'),
(129, 'Mikronesien', 'mikronesien', 'de'),
(145, 'Kosovo', 'kosovo-3', 'pt'),
(145, 'Kosovo', 'kosovo-4', 'de'),
(3, 'Burkina Faso', 'burkina-faso-3', 'pt'),
(3, 'Burkina Faso', 'burkina-faso-4', 'de'),
(19, 'Samoa', 'samoa-3', 'pt'),
(19, 'Samoa', 'samoa-4', 'de'),
(35, 'Guiné-Bissau', 'guine-bissau', 'pt'),
(35, 'Guinea-Bissau', 'guinea-bissau-2', 'de'),
(51, 'Guiné', 'guine', 'pt'),
(51, 'Guinea', 'guinea-2', 'de'),
(66, 'Porto Rico', 'porto-rico-1', 'pt'),
(66, 'Puerto Rico', 'puerto-rico-2', 'de'),
(82, 'Zâmbia', 'zambia-2', 'pt'),
(82, 'Sambia', 'sambia', 'de'),
(98, 'Moldávia', 'moldavia-1', 'pt'),
(98, 'Moldawien', 'moldawien', 'de'),
(114, 'Martinica', 'martinica-1', 'pt'),
(114, 'Martinique', 'martinique-2', 'de'),
(130, 'Ilhas Faroe', 'ilhas-faroe', 'pt'),
(130, 'Färöer Inseln', 'faeroeer-inseln', 'de'),
(146, 'Costa do Marfim', 'costa-do-marfim', 'pt'),
(146, 'Elfenbeinküste', 'elfenbeinkueste', 'de'),
(4, 'Bulgária', 'bulgaria-2', 'pt'),
(4, 'Bulgarien', 'bulgarien', 'de'),
(20, 'Bonaire, Santo Eustatius e Saba', 'bonaire-santo-eustatius-e-saba', 'pt'),
(20, 'Bonaire, Saint Eustatius and Saba', 'bonaire-saint-eustatius-and-saba-1', 'de'),
(36, 'Guam', 'guam-3', 'pt'),
(36, 'Guam', 'guam-4', 'de'),
(52, 'Gambia', 'gambia-2', 'pt'),
(52, 'Gambia', 'gambia-3', 'de'),
(67, 'Território Palestino', 'territorio-palestino-1', 'pt'),
(67, 'Palästinensisches Gebiet', 'palaestinensisches-gebiet', 'de'),
(83, 'Saara Ocidental', 'saara-ocidental', 'pt'),
(83, 'Westsahara', 'westsahara', 'de'),
(99, 'Madagáscar', 'madagascar-3', 'pt'),
(99, 'Madagaskar', 'madagaskar', 'de'),
(115, 'Ilhas Marianas do Norte', 'ilhas-marianas-do-norte', 'pt'),
(115, 'Nördliche Marianneninseln', 'noerdliche-marianneninseln', 'de'),
(131, 'Nicarágua', 'nicaragua-3', 'pt'),
(131, 'Nicaragua', 'nicaragua-4', 'de'),
(147, 'Suíça', 'suica', 'pt'),
(147, 'Schweiz', 'schweiz', 'de'),
(5, 'Bósnia e Herzegovina', 'bosnia-e-herzegovina', 'pt'),
(5, 'Bosnien und Herzegowina', 'bosnien-und-herzegowina', 'de'),
(21, 'Brasil', 'brasil-1', 'pt'),
(21, 'Brasilien', 'brasilien', 'de'),
(37, 'Guatemala', 'guatemala-3', 'pt'),
(37, 'Guatemala', 'guatemala-4', 'de'),
(53, 'Groenlândia', 'groenlandia', 'pt'),
(53, 'Grönland', 'groenland-1', 'de'),
(68, 'Palau', 'palau-3', 'pt'),
(68, 'Palau', 'palau-4', 'de'),
(84, 'Estônia', 'estonia-2', 'pt'),
(84, 'Estland', 'estland', 'de'),
(100, 'São Martinho', 'sao-martinho', 'pt'),
(100, 'Sankt Martin', 'sankt-martin', 'de'),
(116, 'Montserrat', 'montserrat-3', 'pt'),
(116, 'Montserrat', 'montserrat-4', 'de'),
(132, 'Países Baixos', 'paises-baixos', 'pt'),
(132, 'Niederlande', 'niederlande', 'de'),
(148, 'Colômbia', 'colombia-2', 'pt'),
(148, 'Kolumbien', 'kolumbien', 'de'),
(6, 'Barbados', 'barbados-1', 'pt'),
(6, 'Barbados', 'barbados-2', 'de'),
(22, 'Bahamas', 'bahamas-3', 'pt'),
(22, 'Bahamas', 'bahamas-4', 'de'),
(38, 'Ilhas Geórgia do Sul e Sandwich do Sul', 'ilhas-georgia-do-sul-e-sandwich-do-sul', 'pt'),
(38, 'Süd-Georgien und die südlichen Sandwich-Inseln', 'sued-georgien-und-die-suedlichen-sandwich-inseln', 'de'),
(54, 'Gibraltar', 'gibraltar-3', 'pt'),
(54, 'Gibraltar', 'gibraltar-4', 'de'),
(69, 'Portugal', 'portugal-3', 'pt'),
(69, 'Portugal', 'portugal-4', 'de'),
(85, 'Egito', 'egito', 'pt'),
(85, 'Ägypten', 'aegypten', 'de'),
(101, 'Marrocos', 'marrocos', 'pt'),
(101, 'Marokko', 'marokko', 'de'),
(117, 'Mauritânia', 'mauritania-2', 'pt'),
(117, 'Mauretanien', 'mauretanien', 'de'),
(133, 'Noruega', 'noruega-1', 'pt'),
(133, 'Norwegen', 'norwegen', 'de'),
(149, 'China', 'china-2', 'pt'),
(149, 'China', 'china-3', 'de'),
(7, 'Wallis e Futuna', 'wallis-e-futuna', 'pt'),
(7, 'Wallis und Futuna', 'wallis-und-futuna', 'de'),
(23, 'Jersey', 'jersey-3', 'pt'),
(23, 'Jersey', 'jersey-4', 'de'),
(39, 'Grécia', 'grecia-1', 'pt'),
(39, 'Griechenland', 'griechenland', 'de'),
(55, 'Gana', 'gana', 'pt'),
(55, 'Ghana', 'ghana-3', 'de'),
(70, 'Svalbard e Jan Mayen', 'svalbard-e-jan-mayen', 'pt'),
(70, 'Svalbard und Jan Mayen', 'svalbard-und-jan-mayen', 'de'),
(86, 'África do Sul', 'africa-do-sul', 'pt'),
(86, 'Südafrika', 'suedafrika', 'de'),
(102, 'Mônaco', 'monaco-3', 'pt'),
(102, 'Monaco', 'monaco-4', 'de'),
(118, 'Ilha de Man', 'ilha-de-man', 'pt'),
(118, 'Isle of Man', 'isle-of-man-1', 'de'),
(134, 'Namíbia', 'namibia-2', 'pt'),
(134, 'Namibia', 'namibia-3', 'de'),
(150, 'Camarões', 'camaroes', 'pt'),
(150, 'Kamerun', 'kamerun', 'de'),
(8, 'São Bartolomeu', 'sao-bartolomeu', 'pt'),
(8, 'St. Barthélemy', 'st-barthelemy', 'de'),
(24, 'Bielo-Rússia', 'bielo-russia', 'pt'),
(24, 'Weißrussland', 'weissrussland', 'de'),
(40, 'Guiné Equatorial', 'guine-equatorial', 'pt'),
(40, 'Äquatorialguinea', 'aequatorialguinea', 'de'),
(56, 'Omã', 'oma', 'pt'),
(56, 'Oman', 'oman-3', 'de'),
(71, 'Paraguai', 'paraguai', 'pt'),
(71, 'Paraguay', 'paraguay-3', 'de'),
(72, 'Iraque', 'iraque', 'pt'),
(72, 'Irak', 'irak-2', 'de'),
(87, 'Equador', 'equador', 'pt'),
(87, 'Ecuador', 'ecuador-2', 'de'),
(103, 'Uzbequistão', 'uzbequistao', 'pt'),
(103, 'Usbekistan', 'usbekistan', 'de'),
(119, 'Uganda', 'uganda-2', 'pt'),
(119, 'Uganda', 'uganda-3', 'de'),
(135, 'Vanuatu', 'vanuatu-3', 'pt'),
(135, 'Vanuatu', 'vanuatu-4', 'de'),
(9, 'Bermudas', 'bermudas', 'pt'),
(9, 'Bermuda', 'bermuda-1', 'de'),
(25, 'Belize', 'belize-2', 'pt'),
(25, 'Belize', 'belize-3', 'de'),
(41, 'Guadalupe', 'guadalupe-1', 'pt'),
(41, 'Guadeloupe', 'guadeloupe-1', 'de'),
(57, 'Tunísia', 'tunisia-1', 'pt'),
(57, 'Tunesien', 'tunesien', 'de'),
(73, 'Panamá', 'panama-3', 'pt'),
(73, 'Panama', 'panama-4', 'de'),
(88, 'Itália', 'italia-1', 'pt'),
(88, 'Italien', 'italien', 'de'),
(89, 'Vietnã', 'vietna', 'pt'),
(89, 'Vietnam', 'vietnam-3', 'de'),
(104, 'Mianmar', 'mianmar', 'pt'),
(104, 'Myanmar', 'myanmar-3', 'de'),
(120, 'Tanzânia', 'tanzania-2', 'pt'),
(120, 'Tansania', 'tansania', 'de'),
(136, 'Nova Caledônia', 'nova-caledonia', 'pt'),
(136, 'Neu-Kaledonien', 'neu-kaledonien', 'de'),
(10, 'Brunei', 'brunei-3', 'pt'),
(10, 'Brunei', 'brunei-4', 'de'),
(26, 'Rússia', 'russia-1', 'pt'),
(26, 'Russland', 'russland', 'de'),
(42, 'Japão', 'japao', 'pt'),
(42, 'Japan', 'japan-1', 'de'),
(58, 'Jordânia', 'jordania', 'pt'),
(58, 'Jordanien', 'jordanien', 'de'),
(74, 'Polinésia Francesa', 'polinesia-francesa', 'pt'),
(74, 'Französisch Polynesien', 'franzoesisch-polynesien', 'de'),
(90, 'Ilhas Salomão', 'ilhas-salomao', 'pt'),
(90, 'Salomon-Inseln', 'salomon-inseln', 'de'),
(105, 'Mali', 'mali-3', 'pt'),
(105, 'Mali', 'mali-4', 'de'),
(106, 'Macau', 'macau', 'pt'),
(106, 'Macau', 'macau-1', 'de'),
(121, 'Malásia', 'malasia-1', 'pt'),
(121, 'Malaysia', 'malaysia-1', 'de'),
(137, 'Níger', 'niger-3', 'pt'),
(137, 'Niger', 'niger-4', 'de'),
(11, 'Bolívia', 'bolivia-2', 'pt'),
(11, 'Bolivien', 'bolivien', 'de'),
(27, 'Ruanda', 'ruanda-1', 'pt'),
(27, 'Ruanda', 'ruanda-2', 'de'),
(43, 'Guiana', 'guiana', 'pt'),
(43, 'Guyana', 'guyana-1', 'de'),
(59, 'Croácia', 'croacia-1', 'pt'),
(59, 'Kroatien', 'kroatien', 'de'),
(75, 'Papua Nova Guiné', 'papua-nova-guine', 'pt'),
(75, 'Papua Neu-Guinea', 'papua-neu-guinea', 'de'),
(91, 'Etiópia', 'etiopia-1', 'pt'),
(91, 'Äthiopien', 'aethiopien', 'de'),
(107, 'Mongólia', 'mongolia-2', 'pt'),
(107, 'Mongolei', 'mongolei', 'de'),
(122, 'México', 'mexico-2', 'pt'),
(122, 'Mexiko', 'mexiko', 'de'),
(123, 'França', 'franca', 'pt'),
(123, 'Frankreich', 'frankreich', 'de'),
(138, 'Ilha Norfolk', 'ilha-norfolk', 'pt'),
(138, 'Norfolkinsel', 'norfolkinsel', 'de'),
(12, 'Bahrain', 'bahrain-1', 'pt'),
(12, 'Bahrain', 'bahrain-2', 'de'),
(28, 'Sérvia', 'servia', 'pt'),
(28, 'Serbien', 'serbien', 'de'),
(44, 'Guernsey', 'guernsey-2', 'pt'),
(44, 'Guernsey', 'guernsey-3', 'de'),
(60, 'Haiti', 'haiti-3', 'pt'),
(60, 'Haiti', 'haiti-4', 'de'),
(76, 'Peru', 'peru-2', 'pt'),
(76, 'Peru', 'peru-3', 'de'),
(92, 'Somália', 'somalia-2', 'pt'),
(92, 'Somalia', 'somalia-3', 'de'),
(108, 'Ilhas Marshall', 'ilhas-marshall', 'pt'),
(108, 'Marshallinseln', 'marshallinseln', 'de'),
(124, 'Território Britânico do Oceano Índico', 'territorio-britanico-do-oceano-indico', 'pt'),
(124, 'Britisches Territorium des Indischen Ozeans', 'britisches-territorium-des-indischen-ozeans', 'de'),
(139, 'Nigéria', 'nigeria-3', 'pt'),
(139, 'Nigeria', 'nigeria-4', 'de'),
(140, 'Nova Zelândia', 'nova-zelandia', 'pt'),
(140, 'Neuseeland', 'neuseeland', 'de'),
(159, 'Ilha do Natal', 'ilha-do-natal', 'pt'),
(159, 'Weihnachtsinsel', 'weihnachtsinsel', 'de'),
(160, 'Costa Rica', 'costa-rica-3', 'pt'),
(160, 'Costa Rica', 'costa-rica-4', 'de'),
(175, 'São Tomé e Príncipe', 'sao-tome-e-principe', 'pt'),
(175, 'Sao Tome und Principe', 'sao-tome-und-principe', 'de'),
(176, 'Eslováquia', 'eslovaquia-1', 'pt'),
(176, 'Slowakei', 'slowakei', 'de'),
(191, 'Dominica', 'dominica-2', 'pt'),
(191, 'Dominika', 'dominika', 'de'),
(207, 'Trinidad e Tobago', 'trinidad-e-tobago', 'pt'),
(207, 'Trinidad und Tobago', 'trinidad-und-tobago', 'de'),
(223, 'Vaticano', 'vaticano-1', 'pt'),
(223, 'Vatikan', 'vatikan', 'de'),
(239, 'Austrália', 'australia-2', 'pt'),
(239, 'Australien', 'australien', 'de'),
(30, 'Reunion', 'reunion-3', 'pt'),
(30, 'Reunion', 'reunion-4', 'de'),
(151, 'Chile', 'chile-2', 'pt'),
(151, 'Chile', 'chile-3', 'de'),
(152, 'Ilhas Cocos', 'ilhas-cocos', 'pt'),
(152, 'Kokosinseln', 'kokosinseln', 'de'),
(153, 'Canadá', 'canada-3', 'pt'),
(153, 'Kanada', 'kanada', 'de'),
(154, 'República do Congo', 'republica-do-congo', 'pt'),
(154, 'Republik Kongo', 'republik-kongo', 'de'),
(155, 'República Centro-Africana', 'republica-centro-africana', 'pt'),
(155, 'Zentralafrikanische Republik', 'zentralafrikanische-republik', 'de'),
(161, 'Curaçao', 'curacao-2', 'pt'),
(161, 'Curacao', 'curacao-3', 'de'),
(164, 'Suazilândia', 'suazilandia-1', 'pt'),
(164, 'Swasiland', 'swasiland', 'de'),
(165, 'Síria', 'siria-1', 'pt'),
(165, 'Syrien', 'syrien', 'de'),
(166, 'Sint Maarten', 'sint-maarten-2', 'pt'),
(166, 'Sint Maarten', 'sint-maarten-3', 'de'),
(167, 'Quirguistão', 'quirguistao', 'pt'),
(167, 'Kirgisistan', 'kirgisistan', 'de'),
(168, 'Quênia', 'quenia', 'pt'),
(168, 'Kenia', 'kenia-1', 'de'),
(169, 'Sudão do Sul', 'sudao-do-sul', 'pt'),
(169, 'Südsudan', 'suedsudan', 'de'),
(170, 'Suriname', 'suriname-2', 'pt'),
(170, 'Suriname', 'suriname-3', 'de'),
(171, 'Kiribati', 'kiribati-3', 'pt'),
(171, 'Kiribati', 'kiribati-4', 'de'),
(177, 'Coreia do Sul', 'coreia-do-sul', 'pt'),
(177, 'Südkorea', 'suedkorea', 'de'),
(180, 'Kuwait', 'kuwait-2', 'pt'),
(180, 'Kuwait', 'kuwait-3', 'de'),
(181, 'Senegal', 'senegal-3', 'pt'),
(181, 'Senegal', 'senegal-4', 'de'),
(182, 'San Marino', 'san-marino-2', 'pt'),
(182, 'San Marino', 'san-marino-3', 'de'),
(183, 'Serra Leoa', 'serra-leoa', 'pt'),
(183, 'Sierra Leone', 'sierra-leone-2', 'de'),
(184, 'Seychelles', 'seychelles-2', 'pt'),
(184, 'Seychellen', 'seychellen', 'de'),
(185, 'Cazaquistão', 'cazaquistao', 'pt'),
(185, 'Kasachstan', 'kasachstan', 'de'),
(186, 'Ilhas Cayman', 'ilhas-cayman', 'pt'),
(186, 'Cayman Inseln', 'cayman-inseln', 'de'),
(187, 'Cingapura', 'cingapura', 'pt'),
(187, 'Singapur', 'singapur-1', 'de'),
(192, 'Djibouti', 'djibouti-3', 'pt'),
(192, 'Dschibuti', 'dschibuti', 'de'),
(193, 'Dinamarca', 'dinamarca-1', 'pt'),
(193, 'Dänemark', 'daenemark', 'de'),
(196, 'Iémen', 'iemen', 'pt'),
(196, 'Jemen', 'jemen', 'de'),
(197, 'Argélia', 'argelia-1', 'pt'),
(197, 'Algerien', 'algerien', 'de'),
(198, 'Estados Unidos', 'estados-unidos-1', 'pt'),
(198, 'Vereinigte Staaten', 'vereinigte-staaten', 'de'),
(199, 'Uruguai', 'uruguai', 'pt'),
(199, 'Uruguay', 'uruguay-3', 'de'),
(200, 'Mayotte', 'mayotte-3', 'pt'),
(200, 'Mayotte', 'mayotte-4', 'de'),
(201, 'Ilhas Menores Distantes dos Estados Unidos', 'ilhas-menores-distantes-dos-estados-unidos', 'pt'),
(201, 'Kleine vorgelagerte Inseln der Vereinigten Staaten', 'kleine-vorgelagerte-inseln-der-vereinigten-staaten', 'de'),
(202, 'Líbano', 'libano-1', 'pt'),
(202, 'Libanon', 'libanon', 'de'),
(203, 'Santa Lúcia', 'santa-lucia-1', 'pt'),
(203, 'Heilige Lucia', 'heilige-lucia', 'de'),
(208, 'Turquia', 'turquia-1', 'pt'),
(208, 'Truthahn', 'truthahn', 'de'),
(209, 'Sri Lanka', 'sri-lanka-3', 'pt'),
(209, 'Sri Lanka', 'sri-lanka-4', 'de'),
(212, 'Tonga', 'tonga-3', 'pt'),
(212, 'Tonga', 'tonga-4', 'de'),
(213, 'Lithuania', 'lithuania-1', 'pt'),
(213, 'Litauen', 'litauen', 'de'),
(214, 'Luxemburgo', 'luxemburgo-1', 'pt'),
(214, 'Luxemburg', 'luxemburg', 'de'),
(215, 'Libéria', 'liberia-3', 'pt'),
(215, 'Liberia', 'liberia-4', 'de'),
(216, 'Lesoto', 'lesoto-1', 'pt'),
(216, 'Lesotho', 'lesotho-2', 'de'),
(217, 'Tailândia', 'tailandia-1', 'pt'),
(217, 'Thailand', 'thailand-1', 'de'),
(218, 'Territórios Franceses do Sul', 'territorios-franceses-do-sul', 'pt'),
(218, 'Südfranzösische Territorien', 'suedfranzoesische-territorien', 'de'),
(224, 'São Vicente e Granadinas', 'sao-vicente-e-granadinas', 'pt'),
(224, 'St. Vincent und die Grenadinen', 'st-vincent-und-die-grenadinen', 'de'),
(225, 'Emirados Árabes Unidos', 'emirados-arabes-unidos', 'pt'),
(225, 'Vereinigte Arabische Emirate', 'vereinigte-arabische-emirate', 'de'),
(227, 'Antígua e Barbuda', 'antigua-e-barbuda', 'pt'),
(227, 'Antigua und Barbuda', 'antigua-und-barbuda', 'de'),
(228, 'Afeganistão', 'afeganistao', 'pt'),
(228, 'Afghanistan', 'afghanistan-1', 'de'),
(229, 'Anguila', 'anguila-1', 'pt'),
(229, 'Anguilla', 'anguilla-2', 'de'),
(230, 'Ilhas Virgens Americanas', 'ilhas-virgens-americanas', 'pt'),
(230, 'US Jungferninseln', 'us-jungferninseln', 'de'),
(231, 'Islândia', 'islandia-1', 'pt'),
(231, 'Island', 'island', 'de'),
(232, 'Irã', 'ira', 'pt'),
(232, 'Iran', 'iran-3', 'de'),
(233, 'Armênia', 'armenia-2', 'pt'),
(233, 'Armenien', 'armenien', 'de'),
(234, 'Albânia', 'albania-2', 'pt'),
(234, 'Albanien', 'albanien', 'de'),
(240, 'Áustria', 'austria-2', 'pt'),
(240, 'Österreich', 'oesterreich', 'de'),
(241, 'Aruba', 'aruba-3', 'pt'),
(241, 'Aruba', 'aruba-4', 'de'),
(243, 'Ilhas Aland', 'ilhas-aland', 'pt'),
(243, 'Aland-Inseln', 'aland-inseln', 'de'),
(244, 'Azerbaijão', 'azerbaijao', 'pt'),
(244, 'Aserbaidschan', 'aserbaidschan', 'de'),
(245, 'Irlanda', 'irlanda-1', 'pt'),
(245, 'Irland', 'irland', 'de'),
(246, 'Indonésia', 'indonesia-2', 'pt'),
(246, 'Indonesien', 'indonesien', 'de'),
(247, 'Ucrânia', 'ucrania-1', 'pt'),
(247, 'Ukraine', 'ukraine-2', 'de'),
(248, 'Catar', 'catar', 'pt'),
(248, 'Katar', 'katar-1', 'de'),
(249, 'Moçambique', 'mocambique', 'pt'),
(249, 'Mosambik', 'mosambik', 'de');

INSERT INTO `AfroSympla_homepage_hero_setting_translation` (`translatable_id`, `title`, `paragraph`, `locale`) VALUES
(1, 'AfroSympla', 'Gestão de eventos online e venda de ingressos', 'pt'),
(1, 'AfroSympla', 'Online-Eventmanagement und Ticketverkauf', 'de');

INSERT INTO `AfroSympla_help_center_category_translation` (`translatable_id`, `name`, `slug`, `locale`) VALUES
(1, 'Participante', 'participante', 'pt'),
(2, 'Organizador', 'organizador-1', 'pt');

INSERT INTO `AfroSympla_help_center_category_translation` (`translatable_id`, `name`, `slug`, `locale`) VALUES
(1, 'Teilnehmer', 'teilnehmer', 'de'),
(2, 'Veranstalter', 'veranstalter', 'de');

INSERT INTO `AfroSympla_settings` (`key`, `value`) VALUES
('website_description_de', 'Veranstaltungsmanagement und Ticketverkauf'),
('website_description_pt', 'Gestão de eventos e venda de ingressos');

INSERT INTO `AfroSympla_settings` (`key`, `value`) VALUES
('website_keywords_de', 'meine Veranstaltung organisieren, Online-Tickets, Tickets kaufen'),
('website_keywords_pt', 'organizar meu evento, ingressos online, comprar ingressos');

INSERT INTO `AfroSympla_venue_type_translation` (`translatable_id`, `name`, `slug`, `locale`) VALUES
(1, 'Festsaal', 'banquet-hall-de', 'de'),
(2, 'Bar', 'bar-de', 'de'),
(3, 'Boot', 'boat-de', 'de'),
(4, 'Brauerei', 'brewery-de', 'de'),
(5, 'Cafe', 'cafe-de', 'de'),
(6, 'Co-working space', 'co-working-space-de', 'de'),
(7, 'Konferenzzentrum', 'conference-center-de', 'de'),
(8, 'Country Club', 'country-club-de', 'de'),
(9, 'Veranstaltungsfläche', 'event-space-de', 'de'),
(10, 'Galerie', 'gallery-de', 'de'),
(11, 'Fitnessstudio', 'gym-de', 'de'),
(12, 'Hotel', 'hotel-de', 'de'),
(13, 'Dachgeschoss', 'loft-de', 'de'),
(14, 'Treffpunkt', 'meeting-space-de', 'de'),
(15, 'Museum', 'museum-de', 'de'),
(16, 'Restaurant', 'restaurant-de', 'de'),
(17, 'Stadion', 'stadium-de', 'de'),
(18, 'Theater', 'theater-de', 'de'),
(19, 'Andere', 'other-de', 'de');

INSERT INTO `AfroSympla_venue_type_translation` (`translatable_id`, `name`, `slug`, `locale`) VALUES
(1, 'Salão de baile', 'banquet-hall-pt', 'pt'),
(2, 'Bar', 'bar-pt', 'pt'),
(3, 'Barco', 'boat-pt', 'pt'),
(4, 'Cervejaria', 'brewery-pt', 'pt'),
(5, 'Cafeteria', 'cafe-pt', 'pt'),
(6, 'Espaço de coworking', 'co-working-space-pt', 'pt'),
(7, 'Centro de Conferência', 'conference-center-pt', 'pt'),
(8, 'Clube de Campo', 'country-club-pt', 'pt'),
(9, 'Espaço para eventos', 'event-space-pt', 'pt'),
(10, 'Galeria', 'gallery-pt', 'pt'),
(11, 'Academia', 'gym-pt', 'pt'),
(12, 'Hotel', 'hotel-pt', 'pt'),
(13, 'Sótão', 'loft-pt', 'pt'),
(14, 'Ponto de encontro', 'meeting-space-pt', 'pt'),
(15, 'Museu', 'museum-pt', 'pt'),
(16, 'Restaurante', 'restaurant-pt', 'pt'),
(17, 'Estádio', 'stadium-pt', 'pt'),
(18, 'Teatro', 'theater-pt', 'pt'),
(19, 'Outros', 'other-pt', 'pt');

CREATE TABLE AfroSympla_payment_gateway_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, instructions LONGTEXT DEFAULT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_F2ADA7DD2C2AC5D3 (translatable_id), UNIQUE INDEX AfroSympla_payment_gateway_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

ALTER TABLE AfroSympla_payment_gateway_translation ADD CONSTRAINT FK_F2ADA7DD2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES AfroSympla_payment_gateway (id) ON DELETE CASCADE